import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_padding = true
decorations = "buttonless"
# opacity = 0.95
padding = { x = 5, y = 5 }
option_as_alt = "Both"

[font]
size = 15.0
# normal = { family = "SauceCodePro Nerd Font" }
# normal = { family = "FiraCode Nerd Font" }

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[cursor]
style = { shape = "Block", blinking = "Always" }

